### PR TITLE
fixes that allow the project to work with the current firebase cloud …

### PR DESCRIPTION
**Pull request by nxlouie**
firebaseConfig.js change:
screen shot 2019-02-25 at 5 14 16 pm

store.js change:
screen shot 2019-02-25 at 5 16 35 pm

Login.vue change:
the user object is now buried one layer in the response.

package.json change:
npm install did not allow me to download the firebase binaries until I upped the version of firebase in package.json.

### CODE REVIEW

**Comment by Mada75** [comment]
Thanks, fixes docs reference error for me

**Comment by Gene-Dana** [comment]
Thank you !

**Comment by lsbyerley** [comment]
@Mada75 @nxlouie @Gene-Dana have any of you had any luck converting the firebase functions to async/await? In my experience, they still work fine, but catching errors doesn't work as expected. For example, in the resetPassword() method in Login.vue..

    async resetPassword() {
      this.performingRequest = true
    
      try {
        const resetRes = await fb.auth.sendPasswordResetEmail(this.passwordForm.email);
        this.performingRequest = false
        this.passwordResetSuccess = true
        this.passwordForm.email = ''
    
      } catch(err) {
        console.log('passreseterror', err)
        this.performingRequest = false
        this.errorMsg = err.message
      }
    
    }

When intentionally leaving the email field blank, to generate an error, I get this uncaught error in the browser console..

Screen Shot 2019-04-17 at 10 16 40 PM

**Comment by Mada75** [comment]
@lsbyerley I'm not using them, but have just been playing around for an hour and get the same issue, seems to be a firestore issue where it doesn't support async/await yet (seems different with TypeScript).
Here's an out of date video with a link with the latest info below the video:
 [https://www.youtube.com/watch?time_continue=1&v=NgZIb6Uwpjc](url)
firestore advice:
[https://firebase.google.com/docs/functions/terminate-functions](url).

**Comment by lsbyerley** [comment]
Thanks @Mada75.. strange and upsetting they don't support async/await yet.

**Pull request closed without merging**
